# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/go.mikenewswanger.com/kubesolidator
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/src/go.mikenewswanger.com/kubesolidator
  test_codebase:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/go.mikenewswanger.com/kubesolidator
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: go test -v ./...
  build_codebase:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/go.mikenewswanger.com/kubesolidator
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  build_documentation:
    docker:
      - image: felicianotech/docker-hugo:0.32.4
    working_directory: /go/src/go.mikenewswanger.com/kubesolidator
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: sed -i -r "s/^baseURL(\s+)?=.*$/baseURL = \"go.mikenewswanger.com\/kubesolidator\"/" docs/config.toml
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s /go/src/go.mikenewswanger.com/kubesolidator/docs
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - test_codebase:
          requires:
            - checkout_code
      - build_codebase:
          requires:
            - checkout_code
      - build_documentation:
          requires:
            - checkout_code
